spring:
  application:
    name: workflow
server:
  port: 8085
---
spring:
  messages:
    basename: i18n/checkmsg,i18n/dictionary
---
## jpa 配置
spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
---
## 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      #最小空闲连接
      minimum-idle: 5
      #最大连接数
      maximum-pool-size: 50
      #空闲连接超时时间
      idle-timeout: 500000
      #连接最大存活时间
      max-lifetime: 600000
      #连接超时时间
      connection-timeout: 60000
      #用于测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  sql:
    init:
#      data-locations: classpath:init_sql/data.sql
      mode: always
#      schema-locations: classpath:init_sql/schema.sql
---